import React from 'react';
/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 coffeemachine.gltf 
Author: Phrizee (https://sketchfab.com/phrizee)
License: CC-BY-NC-SA-4.0 (http://creativecommons.org/licenses/by-nc-sa/4.0/)
Source: https://sketchfab.com/3d-models/phr-generic-coffee-machine-sultan-8738d2bdb86349d8a769790798bc0b62
Title: PHR Generic Coffee Machine - SULTAN
*/
import { useGLTF } from '@react-three/drei';

export function CoffeeMachineModel(props) {
  const { nodes, materials } = useGLTF(
    './models/coffeeMachine/coffeemachine.gltf',
  );
  return (
    <group
      {...props}
      dispose={null}
      scale={9.6}
      rotation={[-1.565, 0, 0]}
      position={[0, -1.8, 0]}
    >
      <mesh
        geometry={nodes.Object_4.geometry}
        material={materials.M_Coffee}
        rotation={[Math.PI / 2, 0, 0]}
      />
    </group>
  );
}

useGLTF.preload('./models/coffeeMachine/coffeemachine.gltf');
