export const colors = {
  //base colors
  'ct-background': 'var(--background)',
  'ct-sphere1': 'var(--sphere1)',
  'ct-sphere2': 'var(--sphere2)',
  'ct-sphere3': 'var(--sphere3)',
  'ct-sphereNone': 'var(--sphereNone)',
  'ct-accentButtonLeft': 'var(--accentButtonLeft)',
  'ct-accentButtonRight': 'var(--accentButtonRight)',
  'ct-accentButtonLeftHover': 'var(--accentButtonLeftHover)',
  'ct-accentButtonRightHover': 'var(--accentButtonRightHover)',
  'ct-accentButtonLeftActive': 'var(--accentButtonLeftActive)',
  'ct-accentButtonRightActive': 'var(--accentButtonRightActive)',
  'ct-lightGlass': 'var(--lightGlass)',
  'ct-darkGlass': 'var(--darkGlass)',
  'ct-mainText': 'var(--mainText)',

  //start page
  'ct-mainTopCenterWaveLeft': 'var(--mainTopCenterWaveLeft)',
  'ct-mainTopCenterWaveRight': 'var(--mainTopCenterWaveRight)',
  'ct-mainTopLeftWaveLeft': 'var(--mainTopLeftWaveLeft)',
  'ct-mainTopLeftWaveRight': 'var(--mainTopLeftWaveRight)',
  'ct-mainBottomLeftWaveLeft': 'var(--mainBottomLeftWaveLeft)',
  'ct-mainBottomLeftWaveRight': 'var(--mainBottomLeftWaveRight)',
  'ct-mainBottomCenterWaveLeft': 'var(--mainBottomCenterWaveLeft)',
  'ct-mainBottomCenterWaveRight': 'var(--mainBottomCenterWaveRight)',

  'ct-mainLinearWave1': 'var(--mainLinearWave1)',
  'ct-mainLinearWave2': 'var(--mainLinearWave2)',
  'ct-mainLinearWave3': 'var(--mainLinearWave3)',
  'ct-mainLinearWave4': 'var(--mainLinearWave4)',
  'ct-mainLinearWave5': 'var(--mainLinearWave5)',
  'ct-mainLinearWave6': 'var(--mainLinearWave6)',
  'ct-mainLinearWave7': 'var(--mainLinearWave7)',
};
